import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  // Styles globaux
  background: {
    flex: 1,
    justifyContent: "center",
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#FFF8E8",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#3B3030",
    marginBottom: 20,
  },

  // Styles pour les projets
  projectsContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: "#FFF8E8",
    paddingTop: 50,
  },
  projectCard: {
    backgroundColor: "#FFDE95",
    opacity: 0.9,
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 5,
    overflow: "hidden",
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 20,
  },
  projectTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3B3030",
    marginBottom: 15,
  },

  // Styles pour les colonnes
  columnsContainer: {
    flexDirection: "row",
    paddingBottom: 15,
  },
  columnCard: {
    backgroundColor: "#ECDFCC",
    padding: 20,
    marginRight: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
    width: 250,
    alignItems: "center",
  },
  columnTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3B3030",
    marginBottom: 10,
  },
  addColumnContainer: {
    flexDirection: "row",
    marginTop: 20,
  },

  // Styles pour les tâches
  taskCard: {
    backgroundColor: "#FFF1DB",
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 10,
    elevation: 4,
    alignItems: "center",
  },
  taskName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#3B3030",
    marginBottom: 10,
  },
  taskImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
    marginRight: 10,
  },
  previewImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
    marginVertical: 10,
  },

  // Boutons communs
  buttonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 1,
    color: "#3B3030",
  },
  buttonText: {
    color: "#3B3030",
    fontWeight: "bold",
    textAlign: "center",
  },
  buttonTextImg: {
    color: "#3B3030",
    fontWeight: "bold",
    textAlign: "center",
    paddingTop: 15,
  },
  detailButtonText: {
    color: "#3B3030",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
  },
  addButton: {
    padding: 10,
    borderRadius: 30,
    marginBottom: 15,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.5,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 5,
  },
  gradientButton: {
    flexDirection: "row",
    backgroundColor: "#377DFF",
    borderRadius: 30,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 5,
  },
  gradientButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFF",
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#3B3030",
  },
  gradientButtonLogin: {
    flexDirection: "row",
    backgroundColor: "#377DFF",
    borderRadius: 30,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 10,
  },

  // Boutons spécifiques
  viewButton: {
    flexDirection: "row",
    backgroundColor: "#AAB396",
    padding: 10,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    alignSelf: "center",
    fontWeight: "bold",
  },
  viewButtonColumn: {
    flexDirection: "row",
    backgroundColor: "#AAB396",
    padding: 8,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "70%",
    alignSelf: "center",
    marginBottom: 40,
    marginTop: 40,
  },
  editButton: {
    flexDirection: "row",
    backgroundColor: "#5A6EDC",
    padding: 6,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "auto",
  },
  deleteButton: {
    flexDirection: "row",
    backgroundColor: "#FF3B3B",
    padding: 6,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "auto",
  },
  editButtonColumn: {
    flexDirection: "row",
    backgroundColor: "#5A6EDC",
    padding: 6,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "auto",
    marginBottom: 20,
  },
  deleteButtonTasks: {
    flexDirection: "row",
    backgroundColor: "#FF3B3B",
    padding: 6,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "auto",
    marginLeft: 20,
  },

  // Page Mon Compte
  userContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: "#1A1A1A",
    justifyContent: "center",
    alignItems: "center",
  },
  userTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#FBAB7E",
    marginBottom: 20,
  },
  userInfo: {
    backgroundColor: "#252525",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 20,
    width: "100%",
    alignItems: "center",
  },
  userInfoText: {
    fontSize: 18,
    color: "#FBAB7E",
    textAlign: "center",
  },
  logoutButton: {
    backgroundColor: "#FF3B3B",
    padding: 15,
    borderRadius: 10,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  userButtonText: {
    color: "#3B3030",
    fontWeight: "bold",
    fontSize: 16,
  },
  profileIconContainer: {
    alignItems: "center",
    marginBottom: 20,
  },

  // Connexion / Inscription
  loginContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: "#1A1A1A",
  },
  loginTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#FBAB7E",
    marginBottom: 60,
    textAlign: "center",
  },
  input: {
    borderColor: "#DDD",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 50,
    backgroundColor: "#333",
    color: "#FFF",
    marginBottom: 15,
    width: "100%",
    fontSize: 16,
  },
  error: {
    color: "#FF3B3B",
    marginBottom: 10,
    textAlign: "center",
    fontSize: 14,
  },
  message: {
    color: "#4ECCA3",
    marginBottom: 10,
    textAlign: "center",
    fontSize: 14,
  },

  // Boutons (connexion/inscription)
  button: {
    borderRadius: 8,
    marginVertical: 10,
    width: "80%",
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonInnerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
});

export default styles;
